name: Xiaomi SM8250 Kernel Build

on:
  workflow_dispatch:
    inputs:
      Option:
        description: 'What do you want build option?'
        required: true
        type: choice
        options:
          - ksun
          - twrp
          - stock

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        device: [x1q, y2q, z3q, c1q, c2q, r8q]
    runs-on: ubuntu-24.04

    steps:
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential make automake autoconf libtool pkg-config \
            bc bison flex libssl-dev libelf-dev libncurses5-dev libncurses-dev cpio \
            clang lld gcc g++ \
            git curl rsync wget pv \
            python3 python3-pip python-is-python3 \
            openjdk-17-jdk \
            zip unzip p7zip-full tar \
            lz4 xz-utils zlib1g-dev uuid-dev \
            erofs-utils android-sdk-libsparse-utils \
            fuse3 libfuse3-dev f2fs-tools fuse2fs attr e2fsprogs \
            kmod jq

      - name: Import kernel source
        uses: actions/checkout@v5
        with:
          repository: duyyeunuoc/android_kernel_xiaomi_sm8250
          fetch-depth: 1
          clean: true
          submodules: false

      - name: Add susfs4ksu for kernel-4.19
        run: |
          git clone --depth 1 -b kernel-4.19 https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu
          test -d susfs4ksu/ksu_module_susfs
          cp -r susfs4ksu/ksu_module_susfs ./

      - name: Fix build.sh
        run: |
          test -f build.sh
          chmod +x build.sh

      - name: Build for specific device
        run: ./build.sh ${{ matrix.device }} ${{ github.event.inputs.Option }}

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}-${{ github.event.inputs.Option }}-kernel
          path: |
            ./*.zip
            prebuilts/output/**/*.zip
            prebuilts/output/**/*.tar
            prebuilts/output/**/*.img
          if-no-files-found: error
          retention-days: 7
